"""Prefect orchestration flow for Phase 1a baseline training.

Runs Stage 1 (roof) and Stage 2 (corrosion) training sequentially,
then evaluates both on the frozen test set and produces the go/no-go report.

Usage:
    python ml/flows/baseline_flow.py
    # or via Prefect UI:
    prefect deploy -n baseline-training-flow
"""

from pathlib import Path

import mlflow
from prefect import flow, task, get_run_logger


@task(retries=2, retry_delay_seconds=60, timeout_seconds=7200)
def train_stage1_roof(config_path: str) -> str:
    """Train Stage 1 roof footprint model."""
    logger = get_run_logger()
    logger.info(f"Starting Stage 1 roof training with config: {config_path}")

    # Import and run training
    import subprocess
    result = subprocess.run(
        ["python", "ml/baseline/train_stage1_roof.py", "--config", config_path],
        capture_output=True,
        text=True,
        cwd=str(Path(__file__).parent.parent.parent),
    )

    if result.returncode != 0:
        logger.error(f"Stage 1 training failed:\n{result.stderr}")
        raise RuntimeError(f"Stage 1 training failed: {result.stderr[:500]}")

    logger.info("Stage 1 training complete")
    # Return the MLflow run ID for downstream evaluation
    return result.stdout


@task(retries=2, retry_delay_seconds=60, timeout_seconds=7200)
def train_stage2_corrosion(config_path: str) -> str:
    """Train Stage 2 corrosion segmentation model."""
    logger = get_run_logger()
    logger.info(f"Starting Stage 2 corrosion training with config: {config_path}")

    import subprocess
    result = subprocess.run(
        ["python", "ml/baseline/train_stage2_corrosion.py", "--config", config_path],
        capture_output=True,
        text=True,
        cwd=str(Path(__file__).parent.parent.parent),
    )

    if result.returncode != 0:
        logger.error(f"Stage 2 training failed:\n{result.stderr}")
        raise RuntimeError(f"Stage 2 training failed: {result.stderr[:500]}")

    logger.info("Stage 2 training complete")
    return result.stdout


@task(timeout_seconds=1800)
def evaluate_frozen(model_uri: str, frozen_dir: str = "data/frozen_test") -> dict:
    """Evaluate model on frozen real-image test set."""
    logger = get_run_logger()
    logger.info(f"Evaluating model {model_uri} on frozen test set")

    import json
    import subprocess
    output_dir = "ml/baseline/frozen_eval_results"

    result = subprocess.run(
        [
            "python", "ml/baseline/eval_frozen.py",
            "--model-uri", model_uri,
            "--frozen-dir", frozen_dir,
            "--output-dir", output_dir,
        ],
        capture_output=True,
        text=True,
        cwd=str(Path(__file__).parent.parent.parent),
    )

    if result.returncode != 0:
        logger.error(f"Frozen eval failed:\n{result.stderr}")
        raise RuntimeError(f"Frozen eval failed: {result.stderr[:500]}")

    # Read results
    results_path = Path(__file__).parent.parent / "baseline" / "frozen_eval_results" / "frozen_eval_results.json"
    if results_path.exists():
        with open(results_path) as f:
            results = json.load(f)
        logger.info(f"Frozen eval results: {results}")
        return results

    return {"error": "Results file not found"}


@task
def generate_go_nogo_report(
    stage1_results: str,
    stage2_results: str,
    frozen_results: dict,
) -> str:
    """Generate the Phase 1a go/no-go report."""
    logger = get_run_logger()

    report_lines = [
        "# Phase 1a Baseline Report — Go/No-Go Assessment",
        "",
        f"Generated by: Prefect baseline_flow",
        "",
        "## Results Summary",
        "",
        "### Stage 1: Roof Footprint Segmentation",
        "See MLflow experiment logs for detailed metrics.",
        "",
        "### Stage 2: Corrosion Segmentation",
        "See MLflow experiment logs for detailed metrics.",
        "",
        "### Frozen Real Test Set Evaluation",
    ]

    if "error" not in frozen_results:
        for key, value in frozen_results.items():
            if isinstance(value, float):
                report_lines.append(f"- **{key}**: {value:.4f}")
            else:
                report_lines.append(f"- **{key}**: {value}")
    else:
        report_lines.append(f"- ⚠️ Frozen eval not available: {frozen_results.get('error')}")

    report_lines.extend([
        "",
        "## Go/No-Go Decision",
        "",
        "| Corrosion IoU | Decision |",
        "|---|---|",
        "| ≥ 0.45 | ✅ GO — proceed to Phase 1b with light labeling |",
        "| [0.25, 0.45) | ⚠️ CONDITIONAL — full synthetic + DA plan |",
        "| < 0.25 | ❌ NO-GO — revisit task framing |",
        "",
        "## Next Steps",
        "",
        "Based on the go/no-go outcome, either:",
        "1. Proceed to Phase 1b (Maxar tile purchase + Label Studio)",
        "2. Proceed with synthetic data + domain adaptation pipeline",
        "3. Revisit task framing (severity grading, drone-only product)",
    ])

    report = "\n".join(report_lines)

    # Write report
    report_path = Path(__file__).parent.parent / "baseline" / "BASELINE_REPORT.md"
    report_path.write_text(report)
    logger.info(f"Report written to {report_path}")

    return report


@flow(name="baseline-training-flow", version="1.0.0")
def baseline_training_flow(
    stage1_config: str = "ml/baseline/configs/stage1_roof.yaml",
    stage2_config: str = "ml/baseline/configs/stage2_corrosion.yaml",
    frozen_dir: str = "data/frozen_test",
):
    """Orchestrate Phase 1a baseline training and evaluation.

    Steps:
    1. Train Stage 1 roof model
    2. Train Stage 2 corrosion model
    3. Evaluate both on frozen test set
    4. Generate go/no-go report
    """
    logger = get_run_logger()
    logger.info("Starting Phase 1a baseline training flow")

    # Train both stages (could be parallel if on separate GPUs)
    stage1_results = train_stage1_roof(stage1_config)
    stage2_results = train_stage2_corrosion(stage2_config)

    # Evaluate on frozen test set
    # TODO: construct actual model URIs from MLflow run results
    frozen_results = evaluate_frozen(
        model_uri="mlflow:///models/stage2_corrosion/latest",
        frozen_dir=frozen_dir,
    )

    # Generate report
    report = generate_go_nogo_report(stage1_results, stage2_results, frozen_results)
    logger.info("Phase 1a baseline flow complete")

    return report


if __name__ == "__main__":
    baseline_training_flow()
